// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMypLL-_5_6Sq76FAY-1Rq-2HG61UDoQ',
    appId: '1:992626340618:web:b60ee0673eab3cfe9180f3',
    messagingSenderId: '992626340618',
    projectId: 'hackathon23',
    authDomain: 'hackathon23.firebaseapp.com',
    storageBucket: 'hackathon23.appspot.com',
    measurementId: 'G-2LVF8GMTGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgXgtaYWUfYSWWVkjjFk21C-0Mf7NCXLo',
    appId: '1:992626340618:android:5f9012b8fa8416209180f3',
    messagingSenderId: '992626340618',
    projectId: 'hackathon23',
    storageBucket: 'hackathon23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsj9Yk7GV8DjV0ZTM3LGm8JAblZk8jVuI',
    appId: '1:992626340618:ios:448518bfdcf080529180f3',
    messagingSenderId: '992626340618',
    projectId: 'hackathon23',
    storageBucket: 'hackathon23.appspot.com',
    iosClientId:
        '992626340618-4n4r7accmpp2n4hinh62gkdebr5l8ol2.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsj9Yk7GV8DjV0ZTM3LGm8JAblZk8jVuI',
    appId: '1:992626340618:ios:448518bfdcf080529180f3',
    messagingSenderId: '992626340618',
    projectId: 'hackathon23',
    storageBucket: 'hackathon23.appspot.com',
    iosClientId:
        '992626340618-4n4r7accmpp2n4hinh62gkdebr5l8ol2.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );
}
